"use client";
import TestPage from "./_components/AttendanceManager";
import apiHelper from "vinayak-api-helper";

export default function Home() {
  async function setTokenOnLoad() {
    // set bearer token globally
    const accessToken =
      "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQeUt3ZW1kT1RPeVFnLTR0TjRHT1lBdFhMTEl1dmNGd3hGWTJFY29IQzRJIn0.eyJleHAiOjE3NjI3ODc2NzYsImlhdCI6MTc2Mjc1MTY3OSwiYXV0aF90aW1lIjoxNzYyNzUxNjc2LCJqdGkiOiJvbnJ0YWM6ODk1ZGRlNjUtZjVhMC1iNGRmLTlkY2EtMGNjOGYzZWU4ZTJlIiwiaXNzIjoiaHR0cDovLzEyMi4xNjYuMjQ1Ljk3OjgwODAvcmVhbG1zL2lub3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImY3NDNkZTdiLTFiNTctNDU4YS1hMTcyLTQ0NDYyNmIyMzg5NCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImdhdGV3YXktY2xpZW50Iiwic2lkIjoiOGVmYmRjNGEtMzVmYS00YWMyLWE5YmEtNjI1MWM2NDUxYmY1IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1pbm9wcyIsInVtYV9hdXRob3JpemF0aW9uIiwiRUNULUNMTVMtVVNFUiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LWFwcGxpY2F0aW9ucyIsInZpZXctZ3JvdXBzIiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJkZWxldGUtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9yZ2FuaXphdGlvbiBwcm9maWxlIGVtYWlsIiwiYWRkcmVzcyI6e30sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwib3JnIjoiTWlkaGFuaSIsIm5hbWUiOiJVc2VyMSBUZXN0IiwiZ3JvdXBzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1pbm9wcyIsInVtYV9hdXRob3JpemF0aW9uIiwiRUNULUNMTVMtVVNFUiJdLCJlbXBsb3llZUlkIjoiRU1QMDI1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlciIsImdpdmVuX25hbWUiOiJVc2VyMSIsImZhbWlseV9uYW1lIjoiVGVzdCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20ifQ.EvqMsR84agM2m2WGSBB1S3_KcNt8rZlB-lYLykJV0rr4pXVNv8NTj5toQV4F-jrPl9uUum-zPia72KZlUyYYsszNu_hL0EfUy7bfDUQ256NGkzio7XO_ZHpkR4AzaIGiAZtbErgdT_28qYq6mVHI96vJZrYgomjI2vWiP87uVZEX5hF80TUdR7i3a2XwnhAPwTE8zZJhO8A-eCFzlYoVpD7Vr_vv1UOUUfZTZghS_RLxcZGoa5oq2pi23ohvTru52IoZyzVGXRxUe3lp0rdTlEJr66mIOqh4arxymaK6c65OQl--pB2mI1P4BBwr8yQPJ56iYW-AAr4q4G_MNtLtlg";
    apiHelper.setAuthToken(accessToken);
  }

  setTokenOnLoad();
  return <TestPage />;
}
